In [1]:
import chess.pgn
import numpy as np

def pgn_to_numpy(pgn_file):
    with open(pgn_file) as f:
        game = chess.pgn.read_game(f)
    
    board_states = []
    
    board = game.board()
    
    # Iterate through all moves
    for move in game.mainline_moves():
        board.push(move)
        
        # Convert the board state to a numeric representation
        # Create a 8x8 NumPy array to store the pieces
        board_array = np.zeros((8, 8), dtype=int)
        
        # Map each square to a number based on piece type and color
        for square in chess.SQUARES:
            piece = board.piece_at(square)
            if piece is not None:
                # Positive for white, negative for black
                value = piece.piece_type if piece.color == chess.WHITE else -piece.piece_type
                row, col = divmod(square, 8)
                board_array[row][col] = value
        
        # Add the board state to the list
        board_states.append(board_array)
    
    # Convert the list of arrays to a 3D NumPy array
    return np.array(board_states)

# Example usage
pgn_file = "/Users/vishnudvardhan/Downloads/lichess_db_antichess_rated_2024-08.pgn"
board_states_numpy = pgn_to_numpy(pgn_file)
print(board_states_numpy)





[[[ 4  2  3 ...  3  2  4]
  [ 1  1  1 ...  1  1  1]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [-1 -1 -1 ... -1 -1 -1]
  [-4 -2 -3 ... -3 -2 -4]]

 [[ 4  2  3 ...  3  2  4]
  [ 1  1  1 ...  1  1  1]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [-1 -1 -1 ... -1 -1 -1]
  [-4 -2 -3 ... -3 -2 -4]]

 [[ 4  2  3 ...  0  2  4]
  [ 1  1  1 ...  1  1  1]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 3  0  0 ...  0  0  0]
  [-1 -1 -1 ... -1 -1 -1]
  [-4 -2 -3 ... -3 -2 -4]]

 ...

 [[ 0  2  0 ...  0  2  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 4  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  3]]

 [[ 0  2  0 ...  0  2  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 4  0 -4 ...  0  0  0]
  [ 0  0  0 ...  0  0  3]]

 [[ 0  2  0 ...  0  2  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  4 ...  0  0  0]
  [ 0  0  0 ...  0  0  3]]]
